[build]
  command = "npm install --legacy-peer-deps; npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20.5.0"
  CI = "false"

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy - restrict resource loading
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://api.emailjs.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: blob: https: *.supabase.co *.supabase.in;
      connect-src 'self' https://api.emailjs.com *.supabase.co *.supabase.in wss://*.supabase.co wss://*.supabase.in;
      frame-src 'self' https://www.google.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self' https://api.emailjs.com;
      frame-ancestors 'none';
      upgrade-insecure-requests;
    """
    
    # Prevent clickjacking attacks
    X-Frame-Options = "DENY"
    
    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"
    
    # Control referrer information
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Restrict browser features and APIs
    Permissions-Policy = """
      geolocation=(),
      microphone=(),
      camera=(),
      payment=(),
      usb=(),
      magnetometer=(),
      gyroscope=(),
      accelerometer=(),
      ambient-light-sensor=(),
      autoplay=(self),
      encrypted-media=(self),
      fullscreen=(self),
      picture-in-picture=(self)
    """
    
    # Cross-Origin Embedder Policy
    Cross-Origin-Embedder-Policy = "credentialless"
    
    # Cross-Origin Opener Policy
    Cross-Origin-Opener-Policy = "same-origin"
    
    # Cross-Origin Resource Policy
    Cross-Origin-Resource-Policy = "cross-origin"

# Stricter headers for admin routes
[[headers]]
  for = "/management-dashboard*"
  [headers.values]
    # More restrictive CSP for admin area
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline';
      font-src 'self';
      img-src 'self' data: blob: *.supabase.co *.supabase.in;
      connect-src 'self' *.supabase.co *.supabase.in wss://*.supabase.co wss://*.supabase.in;
      frame-src 'none';
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
      upgrade-insecure-requests;
    """
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet, noimageindex"

# Cache control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
